# Generated by Django 3.1.7 on 2021-03-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
