# Generated by Django 3.1.7 on 2021-03-13 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Texto',
        ),
        migrations.RenameField(
            model_name='texto',
            old_name='img',
            new_name='parrafo',
        ),
    ]
