# Generated by Django 3.1.7 on 2021-03-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210313_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='texto',
            name='autor',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='texto',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
